--- 

- hosts: server2
  become: True
  tasks:
    - name: install apache
      package:
        name: apache2
        state: latest
    - name: start and enable apache
      service:
        name: apache2
        state: started
        enabled: true
    - name: create indedx.html
      file:
        path: /var/www/html/index.html
        state: touch
    - name: add a line to index.html
      lineinfile: 
        path: /var/www/html/index.html
        line: "Hello world"


